aliases:
  use:
    Leaflet:
      value: ./dist/renderers/leaflet.mjs
      description: Leaflet is the leading open-source JavaScript library for mobile-friendly interactive maps. It has all the mapping features most developers ever need.
    Maplibre:
      value: ./dist/renderers/maplibre.mjs
      description: MapLibre GL JS is a TypeScript library that uses WebGL to render interactive maps from vector tiles in a browser. The customization of the map comply with the MapLibre Style Spec.
    Openlayers:
      value: ./dist/renderers/openlayers.mjs
      description: OpenLayers makes it easy to put a dynamic map in any web page. It can display map tiles, vector data and markers loaded from any source. OpenLayers has been developed to further the use of geographic information of all kinds.
  width:
    One-Third: 33%
    Half: 50%
    Three-Quarter: 75%
    Full: 100%
  height:
    Small: 200px
    Medium: 30vh
    Huge: 75vh
  center:
    ARGENTINA Buenos Aires: [ -58.3816, -34.6037 ]
    BANGLADESH Dhaka: [ 90.4125, 23.8103 ]
    BRAZIL Sao Paulo: [ -46.6333, -23.5505 ]
    CHINA Beijing: [ 116.4074, 39.9042 ]
    CHINA Shanghai: [ 121.4737, 31.2304 ]
    EGYPT Cairo: [ 31.2357, 30.0444 ]
    INDIA Delhi: [ 77.1025, 28.7041 ]
    INDIA Mumbai: [ 72.8777, 19.0760 ]
    JAPAN Osaka: [ 135.5022, 34.6937 ]
    MEXICO Mexico City: [ -99.1332, 19.4326 ]
    NIGERIA Lagos: [ 3.3792, 6.5244 ]
    PAKISTAN Karachi: [ 67.0011, 24.8607 ]
    PILLIPPINES Manila: [ 120.9842, 14.5995 ]
    TAIWAN Changhua County: [120.5445, 24.0756]
    TAIWAN Hsinchu County: [121.0128, 24.8267]
    TAIWAN Hualien County: [121.6112, 23.9911]
    TAIWAN Kaohsiung City: [120.2667, 22.6333]
    TAIWAN Keelung City: [121.741, 25.131]
    TAIWAN Miaoli County: [120.8152, 24.5734]
    TAIWAN Nantou County: [120.9818101, 23.9512034]
    TAIWAN New Taipei City: [121.457, 25.062]
    TAIWAN Pingtung County: [120.5502695, 22.5468588]
    TAIWAN Taichung City: [120.6736, 24.1477]
    TAIWAN Tainan City: [120.2067478, 22.9963617]
    TAIWAN Taipei City: [121.5182451, 25.0504781]
    TAIWAN Taitung County: [121.1508031, 22.7706117]
    TAIWAN Taoyuan City: [121.297, 24.994]
    TAIWAN Yilan County: [121.7627819, 24.7637321]
    TURKEY Istanbul: [ 28.9784, 41.0082 ]
    USA New York City: [ -74.0059, 40.7128 ]
  zoom:
    Whole world: 0
    Subcontinental area: 2
    Large African country: 5
    Large European country: 6
    Wide area, large metropolitan area: 9
    Metropolitan area: 10
    City: 11
    Town, or city district: 12
    Village, or suburb: 13
    Street: 16
    Block, park, addresses: 17
    Building: 20
  XYZ:
    OSM Carto: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    OSM Bright: https://tile.openstreetmap.jp/styles/osm-bright/512/{z}/{x}/{y}.png
    OSM DE: https://tile.openstreetmap.de/{z}/{x}/{y}.png
    OSM CH: https://tile.osm.ch/switzerland/{z}/{x}/{y}.png
    OSM FR: https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png
    OSM FR Hot: https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png
    OSM BZH: https://tile.openstreetmap.bzh/br/{z}/{x}/{y}.png
    OSM BZH CA: https://tile.openstreetmap.bzh/ca/{z}/{x}/{y}.png
    MemoMaps: https://tileserver.memomaps.de/tilegen/{z}/{x}/{y}.png
    OpenTopoMap: https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png
    Stadia Alidade Smooth: https://tiles.stadiamaps.com/tiles/alidade_smooth/{z}/{x}/{y}{r}.{ext}
    Staida Alidade Smooth Dark: https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.{ext}
    Stadia OSM Bright: https://tiles.stadiamaps.com/tiles/osm_bright/{z}/{x}/{y}{r}.{ext}
    Stadia Outdoors: https://tiles.stadiamaps.com/tiles/outdoors/{z}/{x}/{y}{r}.{ext}
    Stadia Toner:  https://tiles.stadiamaps.com/tiles/stamen_toner/{z}/{x}/{y}{r}.{ext}
    Stadis Toner Light: https://tiles.stadiamaps.com/tiles/stamen_toner_lite/{z}/{x}/{y}{r}.{ext}
    Stadia Water Color: https://tiles.stadiamaps.com/tiles/stamen_watercolor/{z}/{x}/{y}.{ext}
    Stadia Terrain: https://tiles.stadiamaps.com/tiles/stamen_terrain/{z}/{x}/{y}{r}.{ext}
    Stadia Terrain Background: https://tiles.stadiamaps.com/tiles/stamen_terrain_background/{z}/{x}/{y}{r}.{ext}
    BaseMap DE Color: https://sgx.geodatenzentrum.de/wmts_basemapde/tile/1.0.0/de_basemapde_web_raster_farbe/default/GLOBAL_WEBMERCATOR/{z}/{y}/{x}.png
    BaseMap DE Grey: https://sgx.geodatenzentrum.de/wmts_basemapde/tile/1.0.0/de_basemapde_web_raster_grau/default/GLOBAL_WEBMERCATOR/{z}/{y}/{x}.png
    Cycloms: https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png
    FreeMap SK: https://{s}.freemap.sk/T/{z}/{x}/{y}.jpeg
    MtbMap: http://tile.mtbmap.cz/mtbmap_tiles/{z}/{x}/{y}.png
    MapTiler Basic: https://tile.openstreetmap.jp/styles/maptiler-basic-en/512/{z}/{x}/{y}.png
    MapTiler Toner: https://tile.openstreetmap.jp/styles/maptiler-toner-ja/512/{z}/{x}/{y}.png
    OpenMapTiles: https://tile.openstreetmap.jp/styles/openmaptiles/512/{z}/{x}/{y}.png
    TAIWAN Rudymap: https://tile.happyman.idv.tw/map/moi_osm/{z}/{x}/{y}.png
    TAIWAN Happyman GPX: https://tile.happyman.idv.tw/map/gpxtrack/{z}/{x}/{y}.png
    TAIWAN Happyman MOI: https://tile.happyman.idv.tw/map/moi_osm/{z}/{x}/{y}.png
    TAIWAN TERRAIN RGB: https://osmhacktw.github.io/terrain-rgb/tiles/{z}/{x}/{y}.png
    ESRI World Topo: https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}
    ESRI World Imagery: https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
    ESRI World Shaded Relief: https://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}
    ESRI World Ocean: https://server.arcgisonline.com/ArcGIS/rest/services/Ocean/World_Ocean_Base/MapServer/tile/{z}/{y}/{x}
    ESRI World Light Gray: https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}
    ESRI NatGeo World: https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}
  WMTS:
    TAIWAN NLSC: https://wmts.nlsc.gov.tw/wmts
    TAIWAN TERRAIN-RGB: https://osmhacktw.github.io/terrain-rgb/wmts.xml
    TAIWAN TAIPEI-GOV: https://www.historygis.udd.gov.taipei/wmts
    TAIWAN SINICA: https://gis.sinica.edu.tw/tileserver/wmts
    TAIWAN SINICA_TAOYUAN: https://gis.sinica.edu.tw/taoyuan/wmts
    TAIWAN SINICA_TAICHUNG:  https://gis.sinica.edu.tw/taichung/wmts
    TAIWAN SINICA_CHIAYI:  https://gis.sinica.edu.tw/chiayi/wmts
    TAIWAN SINICA_HUALIAN:  https://gis.sinica.edu.tw/hualien/wmts
    TAIWAN SINICA_SHANGHAI: http://gis.sinica.edu.tw/shanghai/wmts
    TAIWAN SINICA_BEIJING:  http://gis.sinica.edu.tw/beijing/wmts
    TAIWAN SINICA_WORLD: https://gis.sinica.edu.tw/worldmap/wmts-proxy
    TAIWAN SINICA_CCTS:  https://gis.sinica.edu.tw/ccts/wmts
    TAIWAN NCU_REMOTE:  https://data.csrsr.ncu.edu.tw/SP/wmts
    TAIWAN NCU_REMOTE_TW: https://data.csrsr.ncu.edu.tw/SP_TW_FC/wmts
    TAIWAN CHIAYI-GOV: https://3dmap.chiayi.gov.tw/wmts/
